version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./symfony/public:/var/www/html
      - ./react/build:/app
    depends_on:
      - php
#      - node

  php:
    image: php:8.3-fpm
    volumes:
      - ./symfony:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_SECRET=your_app_secret
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
#    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "3000:3000"
    depends_on:
      - php
    environment:
      - WATCHPACK_POLLING=true
